[package]
name = "fractals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
num-complex = "0.4.2"
rocket = "0.5.0-rc.2"

[profile.dev.package.image]
opt-level = 3
